  
var app = document.getElementById('subtitle');

var typewriter = new Typewriter(app, {
  loop: false,
  delay: 75,
});

typewriter
  .pauseFor(150)
  .typeString('ieuan ieuan ieuan ieuan ieuan ieuan ieuan ieuan ieuan ieuan ieuan ieuan ieuan ieuan ieuan ieuan ieuan ieuan ieuan ieuan ieuan ieuan ieuan ieuan ieuan ieuan ieuan ieuan ieuan ieuan ieuan ieuan ieuan ieuan ieuan ieuan ieuan ieuan ieuan ieuan ieuan ieuan ieuan ieuan ieuan ieuan ieuan ieuan ieuan ieuan ieuan ieuan ieuan ieuan ieuan ieuan ieuan ieuan ieuan ieuan ieuan ieuan ieuan ieuan ieuan ieuan ieuan ieuan ieuan ieuan ieuan ieuan ieuan ieuan ieuan ieuan ieuan ieuan ieuan ieuan ieuan ieuan ieuan ieuan ieuan ieuan ieuan ieuan ieuan ieuan ieuan ieuan ieuan ieuan ieuan ieuan ieuan ieuan ieuan ieuan ieuan ieuan ieuan ieuan ieuan ieuan ieuan ieuan ieuan ieuan ieuan ieuan ieuan ieuan ieuan ieuan ieuan ieuan ieuan ieuan ieuan ieuan ieuan ieuan ieuan ieuan ieuan ieuan ieuan ieuan ieuan ieuan ieuan ieuan ieuan ieuan ieuan ieuan ieuan ieuan ieuan ieuan ieuan ieuan ieuan ieuan ieuan ieuan ieuan ieuan ieuan ieuan ieuan ieuan ieuan ieuan ieuan ieuan ieuan ieuan ieuan ieuan ieuan ieuan ieuan ieuan ieuan ieuan ieuan ieuan ieuan ieuan ieuan ieuan ieuan ieuan ieuan ieuan ieuan ieuan ieuan ieuan ieuan ieuan ieuan ieuan ieuan ieuan ieuan ieuan ieuan ieuan ieuan ieuan ieuan ieuan ieuan ieuan ieuan ieuan ieuan ieuan ieuan ieuan ieuan ieuan ieuan ieuan ieuan ieuan ieuan ieuan ieuan ieuan ieuan ieuan ieuan ieuan ieuan ieuan ieuan ieuan ieuan ieuan ieuan ieuan ieuan ieuan ieuan ieuan ieuan ieuan ieuan ieuan ieuan ieuan ieuan ieuan ieuan ieuan ieuan ieuan ieuan ieuan ieuan ieuan ieuan ieuan ieuan ieuan ieuan ieuan ieuan ieuan ieuan ieuan ieuan ieuan ieuan ieuan ieuan ieuan ieuan ieuan ieuan ieuan ieuan ieuan ieuan ieuan ieuan ieuan ieuan ieuan ieuan ieuan ieuan ieuan ieuan ieuan ieuan ieuan ieuan ieuan ieuan ieuan ieuan ieuan ieuan ieuan ieuan ieuan ieuan ieuan ieuan ieuan ieuan ieuan ieuan ieuan ieuan ieuan ieuan ieuan ieuan ieuan ieuan ieuan ieuan ieuan ieuan ieuan ieuan ieuan ieuan ieuan ieuan ieuan ieuan ieuan ieuan ieuan ieuan ieuan ieuan ieuan ieuan ieuan ieuan ieuan ieuan ieuan ieuan ieuan ieuan ieuan ieuan ieuan ieuan ieuan ieuan ieuan ieuan ieuan ieuan ieuan ieuan ieuan ieuan ieuan ieuan ieuan ieuan ieuan ieuan ieuan ieuan ieuan ieuan ieuan ieuan ieuan ieuan ieuan ieuan ieuan ieuan ieuan ieuan ieuan ieuan ieuan ieuan ieuan ieuan ieuan ieuan ieuan ieuan ieuan ieuan ieuan ieuan ieuan ieuan ieuan ieuan ieuan ieuan ieuan ieuan ieuan ieuan ieuan ieuan ieuan ieuan ieuan ieuan ieuan ieuan ieuan ieuan ieuan ieuan ieuan ieuan ieuan ieuan ieuan ieuan ieuan ieuan ieuan ieuan ieuan ieuan ieuan ieuan ieuan ieuan ieuan ieuan ieuan ieuan ieuan ieuan ieuan ieuan ieuan ieuan ieuan ieuan ieuan ieuan ieuan ieuan ieuan ieuan ieuan ieuan ieuan ieuan ieuan ieuan ieuan ieuan ieuan ieuan ieuan ieuan ieuan ieuan ieuan ieuan ieuan ieuan ieuan ieuan ieuan ieuan ieuan ieuan ieuan ieuan ieuan ieuan ieuan ieuan ieuan ieuan ieuan ieuan ieuan ieuan ieuan ieuan ieuan ieuan ieuan ieuan ieuan ieuan ieuan ieuan ieuan ieuan ieuan ieuan ieuan ')
  .pauseFor(1500)
  .start();
